// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// mv_multgen_
NumericVector mv_multgen_(NumericMatrix mat, NumericVector vec);
RcppExport SEXP _sdbmsABC_mv_multgen_(SEXP matSEXP, SEXP vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vec(vecSEXP);
    rcpp_result_gen = Rcpp::wrap(mv_multgen_(mat, vec));
    return rcpp_result_gen;
END_RCPP
}
// mv_multcm_
NumericVector mv_multcm_(NumericMatrix mat, NumericVector vec);
RcppExport SEXP _sdbmsABC_mv_multcm_(SEXP matSEXP, SEXP vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vec(vecSEXP);
    rcpp_result_gen = Rcpp::wrap(mv_multcm_(mat, vec));
    return rcpp_result_gen;
END_RCPP
}
// mv_multdm_
NumericVector mv_multdm_(NumericMatrix mat, NumericVector vec);
RcppExport SEXP _sdbmsABC_mv_multdm_(SEXP matSEXP, SEXP vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vec(vecSEXP);
    rcpp_result_gen = Rcpp::wrap(mv_multdm_(mat, vec));
    return rcpp_result_gen;
END_RCPP
}
// sigmoid_Cpp_
double sigmoid_Cpp_(double x, double vmax, double v0, double r);
RcppExport SEXP _sdbmsABC_sigmoid_Cpp_(SEXP xSEXP, SEXP vmaxSEXP, SEXP v0SEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type vmax(vmaxSEXP);
    Rcpp::traits::input_parameter< double >::type v0(v0SEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(sigmoid_Cpp_(x, vmax, v0, r));
    return rcpp_result_gen;
END_RCPP
}
// SDE_Cpp_gen_
NumericVector SDE_Cpp_gen_(NumericVector vec, NumericMatrix dm, NumericMatrix cm, NumericVector randvec);
RcppExport SEXP _sdbmsABC_SDE_Cpp_gen_(SEXP vecSEXP, SEXP dmSEXP, SEXP cmSEXP, SEXP randvecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type vec(vecSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dm(dmSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type cm(cmSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type randvec(randvecSEXP);
    rcpp_result_gen = Rcpp::wrap(SDE_Cpp_gen_(vec, dm, cm, randvec));
    return rcpp_result_gen;
END_RCPP
}
// SDE_Cpp_
NumericVector SDE_Cpp_(NumericVector vec, NumericMatrix dm, NumericMatrix cm, NumericVector randvec);
RcppExport SEXP _sdbmsABC_SDE_Cpp_(SEXP vecSEXP, SEXP dmSEXP, SEXP cmSEXP, SEXP randvecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type vec(vecSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dm(dmSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type cm(cmSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type randvec(randvecSEXP);
    rcpp_result_gen = Rcpp::wrap(SDE_Cpp_(vec, dm, cm, randvec));
    return rcpp_result_gen;
END_RCPP
}
// ODE_Cpp_
NumericVector ODE_Cpp_(NumericVector vec, double h, double Aa, double mu, double BbC, double C1, double C2, double C3, double vmax, double v0, double r);
RcppExport SEXP _sdbmsABC_ODE_Cpp_(SEXP vecSEXP, SEXP hSEXP, SEXP AaSEXP, SEXP muSEXP, SEXP BbCSEXP, SEXP C1SEXP, SEXP C2SEXP, SEXP C3SEXP, SEXP vmaxSEXP, SEXP v0SEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type vec(vecSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type Aa(AaSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type BbC(BbCSEXP);
    Rcpp::traits::input_parameter< double >::type C1(C1SEXP);
    Rcpp::traits::input_parameter< double >::type C2(C2SEXP);
    Rcpp::traits::input_parameter< double >::type C3(C3SEXP);
    Rcpp::traits::input_parameter< double >::type vmax(vmaxSEXP);
    Rcpp::traits::input_parameter< double >::type v0(v0SEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(ODE_Cpp_(vec, h, Aa, mu, BbC, C1, C2, C3, vmax, v0, r));
    return rcpp_result_gen;
END_RCPP
}
// Splitting_JRNMM_gen_Cpp_
NumericMatrix Splitting_JRNMM_gen_Cpp_(double h_i, NumericVector startv, NumericVector grid_i, NumericMatrix dm_i, NumericMatrix cm_i, double mu_i, double C_i, double A, double B, double a, double b, double v0, double r, double vmax);
RcppExport SEXP _sdbmsABC_Splitting_JRNMM_gen_Cpp_(SEXP h_iSEXP, SEXP startvSEXP, SEXP grid_iSEXP, SEXP dm_iSEXP, SEXP cm_iSEXP, SEXP mu_iSEXP, SEXP C_iSEXP, SEXP ASEXP, SEXP BSEXP, SEXP aSEXP, SEXP bSEXP, SEXP v0SEXP, SEXP rSEXP, SEXP vmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type h_i(h_iSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type startv(startvSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type grid_i(grid_iSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dm_i(dm_iSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type cm_i(cm_iSEXP);
    Rcpp::traits::input_parameter< double >::type mu_i(mu_iSEXP);
    Rcpp::traits::input_parameter< double >::type C_i(C_iSEXP);
    Rcpp::traits::input_parameter< double >::type A(ASEXP);
    Rcpp::traits::input_parameter< double >::type B(BSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type v0(v0SEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type vmax(vmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(Splitting_JRNMM_gen_Cpp_(h_i, startv, grid_i, dm_i, cm_i, mu_i, C_i, A, B, a, b, v0, r, vmax));
    return rcpp_result_gen;
END_RCPP
}
// Splitting_JRNMM_Cpp_
NumericMatrix Splitting_JRNMM_Cpp_(double h_i, NumericVector startv, NumericVector grid_i, NumericMatrix dm_i, NumericMatrix cm_i, double mu_i, double C_i, double A, double B, double a, double b, double v0, double r, double vmax);
RcppExport SEXP _sdbmsABC_Splitting_JRNMM_Cpp_(SEXP h_iSEXP, SEXP startvSEXP, SEXP grid_iSEXP, SEXP dm_iSEXP, SEXP cm_iSEXP, SEXP mu_iSEXP, SEXP C_iSEXP, SEXP ASEXP, SEXP BSEXP, SEXP aSEXP, SEXP bSEXP, SEXP v0SEXP, SEXP rSEXP, SEXP vmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type h_i(h_iSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type startv(startvSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type grid_i(grid_iSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dm_i(dm_iSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type cm_i(cm_iSEXP);
    Rcpp::traits::input_parameter< double >::type mu_i(mu_iSEXP);
    Rcpp::traits::input_parameter< double >::type C_i(C_iSEXP);
    Rcpp::traits::input_parameter< double >::type A(ASEXP);
    Rcpp::traits::input_parameter< double >::type B(BSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type v0(v0SEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type vmax(vmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(Splitting_JRNMM_Cpp_(h_i, startv, grid_i, dm_i, cm_i, mu_i, C_i, A, B, a, b, v0, r, vmax));
    return rcpp_result_gen;
END_RCPP
}
// Splitting_JRNMM_output_Cpp_
NumericVector Splitting_JRNMM_output_Cpp_(double h_i, NumericVector startv, NumericVector grid_i, NumericMatrix dm_i, NumericMatrix cm_i, double mu_i, double C_i, double A, double B, double a, double b, double v0, double r, double vmax);
RcppExport SEXP _sdbmsABC_Splitting_JRNMM_output_Cpp_(SEXP h_iSEXP, SEXP startvSEXP, SEXP grid_iSEXP, SEXP dm_iSEXP, SEXP cm_iSEXP, SEXP mu_iSEXP, SEXP C_iSEXP, SEXP ASEXP, SEXP BSEXP, SEXP aSEXP, SEXP bSEXP, SEXP v0SEXP, SEXP rSEXP, SEXP vmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type h_i(h_iSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type startv(startvSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type grid_i(grid_iSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dm_i(dm_iSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type cm_i(cm_iSEXP);
    Rcpp::traits::input_parameter< double >::type mu_i(mu_iSEXP);
    Rcpp::traits::input_parameter< double >::type C_i(C_iSEXP);
    Rcpp::traits::input_parameter< double >::type A(ASEXP);
    Rcpp::traits::input_parameter< double >::type B(BSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type v0(v0SEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type vmax(vmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(Splitting_JRNMM_output_Cpp_(h_i, startv, grid_i, dm_i, cm_i, mu_i, C_i, A, B, a, b, v0, r, vmax));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sdbmsABC_mv_multgen_", (DL_FUNC) &_sdbmsABC_mv_multgen_, 2},
    {"_sdbmsABC_mv_multcm_", (DL_FUNC) &_sdbmsABC_mv_multcm_, 2},
    {"_sdbmsABC_mv_multdm_", (DL_FUNC) &_sdbmsABC_mv_multdm_, 2},
    {"_sdbmsABC_sigmoid_Cpp_", (DL_FUNC) &_sdbmsABC_sigmoid_Cpp_, 4},
    {"_sdbmsABC_SDE_Cpp_gen_", (DL_FUNC) &_sdbmsABC_SDE_Cpp_gen_, 4},
    {"_sdbmsABC_SDE_Cpp_", (DL_FUNC) &_sdbmsABC_SDE_Cpp_, 4},
    {"_sdbmsABC_ODE_Cpp_", (DL_FUNC) &_sdbmsABC_ODE_Cpp_, 11},
    {"_sdbmsABC_Splitting_JRNMM_gen_Cpp_", (DL_FUNC) &_sdbmsABC_Splitting_JRNMM_gen_Cpp_, 14},
    {"_sdbmsABC_Splitting_JRNMM_Cpp_", (DL_FUNC) &_sdbmsABC_Splitting_JRNMM_Cpp_, 14},
    {"_sdbmsABC_Splitting_JRNMM_output_Cpp_", (DL_FUNC) &_sdbmsABC_Splitting_JRNMM_output_Cpp_, 14},
    {NULL, NULL, 0}
};

RcppExport void R_init_sdbmsABC(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
