# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mv_multgen_ <- function(mat, vec) {
    .Call('_sdbmsABC_mv_multgen_', PACKAGE = 'sdbmsABC', mat, vec)
}

mv_multcm_ <- function(mat, vec) {
    .Call('_sdbmsABC_mv_multcm_', PACKAGE = 'sdbmsABC', mat, vec)
}

mv_multdm_ <- function(mat, vec) {
    .Call('_sdbmsABC_mv_multdm_', PACKAGE = 'sdbmsABC', mat, vec)
}

sigmoid_Cpp_ <- function(x, vmax, v0, r) {
    .Call('_sdbmsABC_sigmoid_Cpp_', PACKAGE = 'sdbmsABC', x, vmax, v0, r)
}

SDE_Cpp_gen_ <- function(vec, dm, cm, randvec) {
    .Call('_sdbmsABC_SDE_Cpp_gen_', PACKAGE = 'sdbmsABC', vec, dm, cm, randvec)
}

SDE_Cpp_ <- function(vec, dm, cm, randvec) {
    .Call('_sdbmsABC_SDE_Cpp_', PACKAGE = 'sdbmsABC', vec, dm, cm, randvec)
}

ODE_Cpp_ <- function(vec, h, Aa, mu, BbC, C1, C2, C3, vmax, v0, r) {
    .Call('_sdbmsABC_ODE_Cpp_', PACKAGE = 'sdbmsABC', vec, h, Aa, mu, BbC, C1, C2, C3, vmax, v0, r)
}

Splitting_JRNMM_gen_Cpp_ <- function(h_i, startv, grid_i, dm_i, cm_i, mu_i, C_i, A, B, a, b, v0, r, vmax) {
    .Call('_sdbmsABC_Splitting_JRNMM_gen_Cpp_', PACKAGE = 'sdbmsABC', h_i, startv, grid_i, dm_i, cm_i, mu_i, C_i, A, B, a, b, v0, r, vmax)
}

Splitting_JRNMM_Cpp_ <- function(h_i, startv, grid_i, dm_i, cm_i, mu_i, C_i, A, B, a, b, v0, r, vmax) {
    .Call('_sdbmsABC_Splitting_JRNMM_Cpp_', PACKAGE = 'sdbmsABC', h_i, startv, grid_i, dm_i, cm_i, mu_i, C_i, A, B, a, b, v0, r, vmax)
}

Splitting_JRNMM_output_Cpp_ <- function(h_i, startv, grid_i, dm_i, cm_i, mu_i, C_i, A, B, a, b, v0, r, vmax) {
    .Call('_sdbmsABC_Splitting_JRNMM_output_Cpp_', PACKAGE = 'sdbmsABC', h_i, startv, grid_i, dm_i, cm_i, mu_i, C_i, A, B, a, b, v0, r, vmax)
}

